services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home   # <── hier werden Jobs, Plugins, Config gespeichert
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.ssh/id_ed25519_ci:/var/jenkins_home/.ssh/id_ed25519_ci:ro
      - /root/.ssh/id_ed25519_ci.pub:/var/jenkins_home/.ssh/id_ed25519_ci.pub:ro
      - /root/.ssh/config:/var/jenkins_home/.ssh/config:ro
      - /root/.ssh/known_hosts:/var/jenkins_home/.ssh/known_hosts:ro

    restart: unless-stopped

volumes:
  jenkins_home:
