version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile.jenkins
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      # Jenkins persistent data
      - jenkins_home:/var/jenkins_home

      # Zugriff auf Docker
      - /var/run/docker.sock:/var/run/docker.sock

      # SSH-Schlüssel + Config
      - ./jenkins_ssh/id_ed25519_ci:/var/jenkins_home/.ssh/id_ed25519_ci:ro
      - ./jenkins_ssh/id_ed25519_ci.pub:/var/jenkins_home/.ssh/id_ed25519_ci.pub:ro
      - ./jenkins_ssh/config:/var/jenkins_home/.ssh/config:ro
      - ./jenkins_ssh/known_hosts:/var/jenkins_home/.ssh/known_hosts:ro

    restart: unless-stopped

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8081:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    restart: unless-stopped

volumes:
  jenkins_home:
