apiVersion: v1
kind: PersistentVolume
metadata:
  name: ci-app-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/c/U/benedikt.wiesner/OneDrive - Brainlab AG/Documents/Docker/ci-app/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ci-app-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
