apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ci-app
  template:
    metadata:
      labels:
        app: ci-app
    spec:
      containers:
        - name: ci-app
          image: ci-app:latest
          imagePullPolicy: Never   # weil du lokal baust
          ports:
            - containerPort: 5000
          resources:
            limits:
              memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: ci-app-service
spec:
  type: LoadBalancer
  selector:
    app: ci-app
  ports:
    - port: 5000
      targetPort: 5000
