apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
      - job_name: 'ci-app'
        static_configs:
          - targets: ['ci-app-service:5000']
      - job_name: 'cadvisor'
        static_configs:
          - targets: ['cadvisor-service:8080']
