pipeline {
    agent any

    environment {
        DOCKER_COMPOSE = "docker compose -f config/docker-compose.yml"
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'git@github.com:benedikt-wiesner-bl/ci-app.git',
                    credentialsId: 'github-ci-key'
            }
        }

        stage('Build Docker Image') {
            steps {
                dir("${env.WORKSPACE}") {
                    sh 'docker build -t ci-app:latest -f infrastructure/Dockerfile .'
                }
            }
        }

        stage('Run Tests') {
            steps {
                sh 'docker run --rm ci-app:latest pytest -q'
            }
        }

        stage('Deploy (only ci-app)') {
            steps {
                sh '''
                    $DOCKER_COMPOSE stop ci-app || true
                    $DOCKER_COMPOSE rm -f ci-app || true
                    $DOCKER_COMPOSE build ci-app
                    docker ps -q --filter "publish=5001" | xargs -r docker stop
                    $DOCKER_COMPOSE up -d ci-app
                '''
            }
        }
    }

    post {
        always {
            sh 'docker ps -a'
        }
        success {
            echo "✅ Deployment erfolgreich!"
        }
        failure {
            echo "❌ Deployment fehlgeschlagen!"
        }
    }
}
